spring:
  application:
      name: MMT
  datasource:
    url: jdbc:postgresql://localhost:5432/MMT_Clone
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mmtclone@gmail.com
    password: dbmu kjwc letc bsll
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

logging:
  level:
    root: INFO
    com.practice.MMT: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"



